### ISSUE TITLE
Queries data cache is not working properly

### ISSUE THREAD

**Issue by abgonzalez93** [latitude-dev/latitude#380]
### Environment

- Node version (`node -v`): 18.20.2
- npm version (`npm -v`): 10.5.2
- Latitude CLI version (`latitude --version`): 1.5.0
- Latitude project version (check `latitude.json` at the root of your project): 1.1.2
- OS: Ubuntu 22.04.3
- Browser: Firefox 125.0.3 & Google Chrome 124.0.6367.119

## Actual Behaviour

I am encountering an issue where I am fetching data from an **SQL endpoint** that I recently **modified**. However, the browser **does not seem to detect the changes** even after forcing a browser cache refresh (**Ctrl + Shift + R**).
When accessing the endpoint via URL directly, the **JSON of the new data is retrieved**.
Additionally, accessing the endpoint in **another browser also reflects the updated data**.

_**Endpoint modified in current browser**_

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/32d19d80-1851-4761-83d7-54280efbde85)

**_Endpoint JSON with new data_**

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/0025339f-8eef-4b4e-8db4-020e9c446215)

_**Endpoint opened in another browser**_

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/5293853d-be5c-4668-b798-56348c38c5ec)

**Comment by csansoon** [comment]
👋 Hi! Is this happening in the Latitude project's views, or are you only using Latitude as an API server and building the frontend somewhere else?

**Comment by abgonzalez93** [comment]
I'm using Latitude as an API server (built on WSL2) and fetching data from it endpoints to a Vue3 project

**Comment by csansoon** [comment]
Hmmm. Check that your frontend is actually sending requests to the Latitude server, and if the response does contain the actual data.

To do that, open the dev tools in your browser, go to "Network", and look for the fetch requests to the server (filtering for "Fetch" might help finding them). If you find them, you can see contents of both the request and the response.
<img width="550" alt="image" src="https://github.com/latitude-dev/latitude/assets/57395395/6db4f16e-434c-42ae-b3db-6473b11b673d">

This error could be one of these:
1. The request has not been sent.
2. The request has been sent with the wrong parameters.
3. The request has been sent with the correct parameters, but the response is empty
4. The request has been sent with the correct parameters and responded with the correct payload, but it is not correctly rendered in the frontend.

If it's either 1, 2 or 3, it seems it has something to do with your Vue application somehow not handling the request properly. Otherwise, if it's the second case, it's an error with Latitude.

**Comment by abgonzalez93** [comment]
I'm getting now the data updated (after a while). Could it be something about the ttl config in source.yml?

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/9d31e5b9-6a39-4e9d-8f49-091ce0b962cd)

![imagen](https://github.com/latitude-dev/latitude/assets/39385878/ef706a9f-1a96-44eb-b7c8-76660813cf8d)

**Comment by csansoon** [comment]
I see. Yes, the `ttl` is included in the response header and it seems like the browser caches the response and it seems like currently there is no way from Latitude to invalidate it. I'll open an issue with the specifics and will take a look at it.

Disabling the cache in frontend should update it though. Reloading with Ctrl+Shift+R only works for assets and resources from the webpage that are available in the initial HTML, but not for code-triggered requests like these ones. In order to disable your browser's cache for any request, you must open your dev tools, go to Network, and enable the "disable cache" option.

**Comment by csansoon** [comment]
Issue moved to https://github.com/latitude-dev/latitude/issues/381

**Comment by csansoon** [comment]
Thanks for reporting @abgonzalez93! Will take a look asap
