### ISSUE TITLE
[Question] API contract documentation?

### ISSUE THREAD

**Issue by tarasyarema** [latitude-dev/latitude#411]
## Request Type

- [ ] Small Fix (wording, errors, typos, etc.)
- [ ] Explanation Improvement (make a description clearer for the reader of the docs)
- [ ] Walkthrough Request (new tutorial for a particular feature or use case)
- [X] Other

## Description

I'm working on a project that offers a way to interact and transform data from Google Sheets, and one of the features I wanted to implement is offer an API with the final transformation output. After seeing this project I believe that it could be possible to abstract or document your expected Api contract so that instead of running the Latitude API locally, it could use an external API. Similar to how some LLM clients work implementing the same OpenAI interface.

I had a look at the `LatitudeApi` implementation and the `QueryResult` type, and it seems pretty straightforward. What do you think about me trying it out and coming back to you with a demo or example, and maybe eventually documenting it in the repo somewhere. I imagine that someone would love to make use of the components but with a "bring your own API" kind of situation.

### References

- [`QueryResultPayload`](https://github.com/latitude-dev/latitude/blob/main/packages/query_result/src/index.ts)
- [`LatitudeApi`](https://github.com/latitude-dev/latitude/blob/main/packages/client/core/src/data/api.ts)

## If improving on existing content, where is that content located?

N/A

## Are you interested in contributing this improvement to the docs?

Yes

**Comment by tarasyarema** [comment]
As a side note, I see that probably the part of the parameters for example would require specific implementation, and also I could not find how the API is setting auth headers, is that implemented somewhere?

**Comment by geclos** [comment]
Key @tarasyarema what frontend stack are you working with? I ask because we just released native [React components](https://docs.latitude.so/react/components/visualizations/area-chart). Default exports are wired with Latitude's API for ease of use but we also expose api-agnostic components ([example](https://github.com/latitude-dev/latitude/blob/827e9f72154074778a206e7359ed3889ec2b2de6/packages/client/react/src/lib/visualizations/raw/charts/AreaChart.tsx)) that take a 'data' object, so you can effectively bring your data from wherever you want.  Would this solve your use case?

**Comment by tarasyarema** [comment]
Ok, that is a nice point! Indeed, with those components you could just use them with your own data on top of them. I guess these might be much simpler than actually trying to plug in the whole provider and all, right? Feel free to close the issue :D
