### ISSUE TITLE
Dynamic prompting

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude#540]
## Feature Description

Based on the dynamic queries engine, create a new dynamic prompts feature to generate AI responses based on user-defined prompts.

Prompts should:
 - Use Latitude's custom syntax to define the prompt based on parameters and logic.
 - Automatically create API endpoints for each prompt, both for full and streamed responses.
 - Be runnable and debuggable from the CLI

## Example

https://github.com/latitude-dev/latitude/assets/57395395/e358dfd8-143c-403a-9582-9c28aedae967

## Status

- [x] Dynamic prompts engine
- [x] CLI command
- [x] Automatic endpoint
- [ ] Documentation
- [ ] React package compatibility
- [ ] Latitude Views compatibility
- [ ] Vscode syntax highlighting 

## Notes

- [ ] Add a custom "SQL" mode to compiler, where it does not ignore logic from inside SQL comments / strings when it is not enabled.
- [ ] Add custom interpolation for query results. Printing `{results}` should automatically interpolate a JSON or a Markdown table to the compiled prompt.

**Comment by cesr** [comment]
Feedback after testing:

1. I think it's weird to have `latitude run` for queries and `latitude prompt` for prompts
2. How to send system vs user prompts?
3. When interpolating a prompt, it adds it with parenthesis
4. I would like an easier way to embed my data in prompts instead of having to run a loop over the results
